[package]
name = "plum3-de-nyx"
version = "0.1.0"
description = "Plum3, éditeur Markdown local-first"
authors = ["Ph3yNyx"]
edition = "2021"

[lib]
name = "plum3_de_nyx_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-png"] }
serde = { version = "1", features = ["derive"] }
pulldown-cmark = { version = "0.13", default-features = false, features = ["html"] }
docx-rs = "0.4.20"
tauri-plugin-opener = "2.5.4"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
rfd = "0.15"
printpdf = "0.9.1"
